#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# use-env.sh — switch the cloud container between the TEST and LIVE profiles.
#
#   bash scripts/cloud/use-env.sh test    # default: TEST-2026-27 session
#   bash scripts/cloud/use-env.sh live    # 2026-27, the real school's money
#   bash scripts/cloud/use-env.sh --show  # which profile is active
#
# Both profiles talk to the SAME Supabase project, because that is how this app
# actually works. The safety boundary is the session label, not the schema:
# `APP_MODE=test` would point at the `test` schema, which the repo documents as
# a proposal that was never adopted and is therefore empty. So both profiles run
# APP_MODE=production and differ in which session an agent reaches for first.
# See docs/cloud-environment.md and Hard Safety Rule 6 in CLAUDE.md.
# ---------------------------------------------------------------------------
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
VAULT="${VEERPATTA_VAULT:-$HOME/.veerpatta/secrets.env}"
MARKER="$REPO_ROOT/.env.profile"

profile="${1:-test}"

if [ "$profile" = "--show" ] || [ "$profile" = "show" ]; then
  if [ -f "$MARKER" ]; then cat "$MARKER"; else echo "no profile written yet"; fi
  exit 0
fi

case "$profile" in
  test|live) ;;
  *) echo "usage: use-env.sh [test|live|--show]" >&2; exit 2 ;;
esac

if [ ! -f "$VAULT" ]; then
  echo "No secret vault at $VAULT — run scripts/cloud/bootstrap.sh first." >&2
  exit 1
fi

set -a; . "$VAULT"; set +a

emit() { # emit NAME — only if the vault actually has a value
  local name="$1" value="${!1:-}"
  [ -n "$value" ] && printf '%s="%s"\n' "$name" "$value"
  return 0
}

{
  echo "# GENERATED by scripts/cloud/use-env.sh — do not edit, do not commit."
  echo "# profile: $profile"
  echo
  echo "# --- Supabase (live project; the session label is the safety boundary) ---"
  emit NEXT_PUBLIC_SUPABASE_URL
  emit NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
  emit SUPABASE_SERVICE_ROLE_KEY
  echo
  echo "# --- App ---"
  echo "APP_MODE=production"
  emit NEXT_PUBLIC_SCHOOL_NAME
  emit NEXT_PUBLIC_APP_MODE
  echo "NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL:-http://localhost:3000}"
  emit NEXT_PUBLIC_SENTRY_DSN
  emit SENTRY_AUTH_TOKEN
  emit CRON_SECRET
  echo
  echo "# --- MCP / document bridge ---"
  emit SCHOOLFEES_DOC_TOKEN
  emit SCHOOLFEES_WORKER_MCP_URL
  emit SCHOOLFEES_WORKER_MCP_TOKEN
  echo "SCHOOLFEES_MCP_HOST=127.0.0.1"
  echo "SCHOOLFEES_MCP_PORT=4317"
  echo "SCHOOLFEES_MCP_PATH=/mcp"
  echo "SCHOOLFEES_MCP_ALLOWED_HOSTS=127.0.0.1,localhost"
  echo
  if [ "$profile" = "test" ]; then
    echo "# --- TEST profile: agents default to the sandbox session ---"
    echo "SCHOOLFEES_MCP_DEFAULT_SESSION=TEST-2026-27"
    echo "REPAYMENT_PLANS=1"
  else
    echo "# --- LIVE profile: this is the school's real 2026-27 money ---"
    echo "SCHOOLFEES_MCP_DEFAULT_SESSION=2026-27"
  fi
} > "$REPO_ROOT/.env.local"

chmod 600 "$REPO_ROOT/.env.local"

if [ "$profile" = "test" ]; then
  printf 'test  (session TEST-2026-27, repayment plans on)\n' > "$MARKER"
else
  printf 'live  (session 2026-27 — REAL school financial records)\n' > "$MARKER"
fi

echo "profile -> $(cat "$MARKER")"
echo "wrote    $REPO_ROOT/.env.local ($(grep -c '=' "$REPO_ROOT/.env.local") values)"
[ "$profile" = "live" ] && echo "WARNING: live session selected. Hard Safety Rule 6 applies — no test data, no test payments." || true
